//* This file is part of the MOOSE framework
//* https://www.mooseframework.org
//*
//* All rights reserved, see COPYRIGHT for full restrictions
//* https://github.com/idaholab/moose/blob/master/COPYRIGHT
//*
//* Licensed under LGPL 2.1, please see LICENSE for details
//* https://www.gnu.org/licenses/lgpl-2.1.html

#pragma once

#include "StrainEnergyDensity.h"
#include "MathUtils.h"

/**
 * Analytically computes the elasticity compliance sensitivity with respect to the physical density
 */
class AnalyticComplianceSensitivity : public StrainEnergyDensity
{
public:
  static InputParameters validParams();

  AnalyticComplianceSensitivity(const InputParameters & parameters);

  virtual void computeQpProperties() override;

protected:
  /// Sensitivity material generated by this error
  MaterialProperty<Real> & _sensitivity;
  /// Physical density variable
  const VariableValue & _physical_density;
  /// Physical density variable name
  const MaterialPropertyName _physical_density_name;
  /// Young's modulus of the material
  const MaterialProperty<Real> & _youngs_modulus;
  /// E0
  const MaterialProperty<Real> & _E0;
  /// Emin
  const MaterialProperty<Real> & _Emin;
  /// power
  const MaterialProperty<Real> & _power;
};
